name: boq
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - torch
      - torchvision
      - lightning
      - faiss-cpu
      - pytorch-metric-learning
      - pandas
      - tensorboard
      - xformers
      - rich