name: boq
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - omegaconf
  - pip:
      - torch
      - torchvision
      - lightning
      - faiss-cpu
      - pytorch-metric-learning
      - pandas
      - tensorboard
      - xformers
      - rich
      - iopath
      - omegaconf
      - scikit-learn
      - scikit-learn-intelex
      - submitit
      - termcolor